### ISSUE TITLE
CGAL cannot add subdirectory

### ISSUE THREAD

**Issue by mcbrs1a** [vigente/gerardus#107]
libCGAL is configured
-- Sources for CGAL component library 'CGAL_Core/CMakeLists.txt' detected
CMake Error at cpp/src/third-party/CGAL-4.2/src/CMakeLists.txt:81 (add_subdirectory):
  add_subdirectory given source
  "/home/putz/PreClin/gerardus/cpp/src/third-party/CGAL-4.2/src/CGAL_Core/CMakeLists.txt"
  which is not an existing directory.
Call Stack (most recent call first):
  cpp/src/third-party/CGAL-4.2/src/CMakeLists.txt:139 (configure_component)

**Comment by rcasero** [comment]
This was a bug in CGAL, perhaps due to some small change in how cmake processes strings.

The problem was in `cpp/src/third-party/CGAL-4.2/src/CMakeLists.txt`.

In order to get a list of directories for `add_subdirectory()`, it was trying to remove the string "//CMakeLists.txt" from the full path string. Perhaps in the past the double "//" was parsed as "/", but now it isn't. So the filename was not being removed, and then `add_subdirectory()` was getting a filename instead of a dirname.

In any case, the solution was changing changing "//CMakeLists.txt" by "/CMakeLists.txt".

This fixed in commit 6d87d7543e4d587de16d89bc97fa8336a2e4ecef

**Comment by fvilca** [comment]
Thank so much. It works fine, the solution was changing "//CMakeLists.txt" by "/CMakeLists.txt".

instalando CGAL 4.5.1 sobre Ubuntu 16,
tuve este error: 
CMake Error at src/CMakeLists.txt:81 (add_subdirectory): cgal
solo cambie   "//CMakeLists.txt" por  "/CMakeLists.txt".
y funciona
